In [41]:
# Guide: https://www.youtube.com/watch?v=v3SePt3fr9g

import pandas as pd
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

# ---------------------------------------------------------
# 1. Load the data
# ---------------------------------------------------------
responses = pd.read_csv("../student-responses.csv")

# ---------------------------------------------------------
# 2. Create embeddings using SentenceTransformer

q1 = responses.iloc[:, 12].dropna().astype(str).tolist()

topic_model = BERTopic(embedding_model="all-MiniLM-L6-v2")

topics, probs = topic_model.fit_transform(q1)

In [42]:
# ---------------------------------------------------------
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,175,-1_the_quantitative_of_categorical,"[the, quantitative, of, categorical, is, was, ...",[One variable that was examined was the percen...
1,0,91,0_bar_smaller_the_which,"[bar, smaller, the, which, quantitative, was, ...",[* which bar was smaller (categorical)\r\n\r\n...
2,1,48,1_the_variable_graph_is,"[the, variable, graph, is, was, would, be, var...",[The type of graph was a variable that was exa...
3,2,46,2_circle_triangle_or_was,"[circle, triangle, or, was, the, bar, categori...",[triangle or circle bar--categorical \r\n\r\nt...
4,3,43,3_were_the_variables_examined,"[were, the, variables, examined, and, variable...","[The variables examined were quantitative. , T..."
5,4,37,4_quantitative_answer_students_correct,"[quantitative, answer, students, correct, cate...",[Accuracy of answers may have been a variable ...
6,5,22,5_blocks_block_the_variable,"[blocks, block, the, variable, we, height, qua...","[categorial - the blocks, the height of the bl..."
7,6,19,6_color_categorical_block_quantitative,"[color, categorical, block, quantitative, shap...","[time- quantitative, shape-categorical, color-..."
8,7,18,7_graph_categorical_larger_bar,"[graph, categorical, larger, bar, graphs, smal...",[2D or 3D bar graph - categorical\r\n\r\nColor...
9,8,14,8_categorical_get_could_fc22t9tgcczie7zs8skivp...,"[categorical, get, could, fc22t9tgcczie7zs8ski...",[One variable could’ve been gender (categorica...
10,9,14,9_3d_2d_effectiveness_people,"[3d, 2d, effectiveness, people, graphs, vs, ca...","[2d : quantitative\r\n\r\n3d: quantitative, Pe..."
11,10,14,10_chart_3d_ratio_the,"[chart, 3d, ratio, the, of, digital, data, and...",[The study examined several key variables. Cha...
12,11,12,11_type_description_calving_categorical,"[type, description, calving, categorical, cow,...","[graphical encoding types, which are categoric..."
13,12,11,12_reading_accuracy_graph_used,"[reading, accuracy, graph, used, accurate, to,...",[Dependent variable : accuracy of reading \r\n...

In [43]:
topic_model.get_topic(0)

[('bar', np.float64(0.07369565012100093)),
 ('smaller', np.float64(0.05832434776320089)),
 ('the', np.float64(0.05259447223523653)),
 ('which', np.float64(0.049872126928872114)),
 ('quantitative', np.float64(0.04691974033528227)),
 ('was', np.float64(0.046913836185220915)),
 ('categorical', np.float64(0.042313632202986465)),
 ('larger', np.float64(0.04197349586779044)),
 ('to', np.float64(0.04167173423287256)),
 ('is', np.float64(0.03924388200635531))]

In [44]:
topic_model.get_representative_docs(0)

['* which bar was smaller (categorical)\r\n\r\n* by how much smaller was the bar compared to the larger one (quantitative)',
 'Which bar was smaller- categorical. Proportion of how much smaller the bar was to the larger bar-quantitative.\xa0',
 'which bar was larger which is categorical and how much smaller the smaller bar was which is quantitative\xa0']

In [45]:
df = pd.DataFrame({"topic": topics, "document": q1})
df.head()

   topic                                           document
0      2            Circle and Triangle graph. Quantitative
1      6        Model size- quantitative color- categorical
2     -1  The height which was quantitative and the othe...
3      5  There were a few variables that were examined,...
4      8  One variable could’ve been gender (categorical...

In [46]:
topic_model.visualize_topics()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'customdata': array([[0, 'bar | smaller | the | which | quantitative', 91],
                                   [1, 'the | variable | graph | is | was', 48],
                                   [2, 'circle | triangle | or | was | the', 46],
                                   [3, 'were | the | variables | examined | and', 43],
                                   [4, 'quantitative | answer | students | correct | categorical', 37],
                                   [5, 'blocks | block | the | variable | we', 22],
                                   [6, 'color | categorical | block | quantitative | shape', 19],
                                   [7, 'graph | categorical | larger | bar | graphs', 18],
                                   [8,
                                    'categorical | get | could | fc22t9tgcczie7zs8skivpg12cmajttaj2mbi7lo | his',
                                    14],
                                   [9, '3d | 2d | effectiveness | people | graphs', 14],
                                   [10, 'chart | 3d | ratio | the | of', 14],
                                   [11, 'type | description | calving | categorical | cow', 12],
                                   [12, 'reading | accuracy | graph | used | accurate', 11]], dtype=object),
              'hovertemplate': '<b>Topic %{customdata[0]}</b><br>%{customdata[1]}<br>Size: %{customdata[2]}',
              'legendgroup': '',
              'marker': {'color': '#B0BEC5',
                         'line': {'color': 'DarkSlateGrey', 'width': 2},
                         'size': {'bdata': 'WzAuKyUWExIODg4MCw==', 'dtype': 'i1'},
                         'sizemode': 'area',
                         'sizeref': 0.056875,
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': {'bdata': 'bTbNQJsMK0GqfOVAkXwuQY61yUCohNtALY+dQN2GokAEUKJA6zNAQMnbXUD1/ZhAlyGKQA==', 'dtype': 'f4'},
              'xaxis': 'x',
              'y': {'bdata': '6uN+QILnMUGxnYhAJlc1QUCRY0BGfndAYjYsP7DXDEC2OZU+AsVBP9uBiD9jKrQ/UtDCPw==', 'dtype': 'f4'},
              'yaxis': 'y'}],
    'layout': {'annotations': [{'showarrow': False,
                                'text': 'D1',
                                'x': np.float32(2.5526934),
                                'y': np.float32(6.6407905),
                                'yshift': 10},
                               {'showarrow': False,
                                'text': 'D2',
                                'x': np.float32(7.5469584),
                                'xshift': 10,
                                'y': np.float32(13.033843)}],
               'height': 650,
               'hoverlabel': {'bgcolor': 'white', 'font': {'family': 'Rockwell', 'size': 16}},
               'legend': {'itemsizing': 'constant', 'tracegroupgap': 0},
               'margin': {'t': 60},
               'shapes': [{'line': {'color': '#CFD8DC', 'width': 2},
                           'type': 'line',
                           'x0': np.float32(7.5469584),
                           'x1': np.float32(7.5469584),
                           'y0': np.float32(0.24773753),
                           'y1': np.float32(13.033843)},
                          {'line': {'color': '#9E9E9E', 'width': 2},
                           'type': 'line',
                           'x0': np.float32(2.5526934),
                           'x1': np.float32(12.541224),
                           'y0': np.float32(6.6407905),
                           'y1': np.float32(6.6407905)}],
               'sliders': [{'active': 0,
                            'pad': {'t': 50},
                            'steps': [{'args': [{'marker.color': [['red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 0',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  'red', '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 1',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 2',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 3',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 4',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 5',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 6',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 7',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 8',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 9',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 10',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 11',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  'red']]}],
                                       'label': 'Topic 12',
                                       'method': 'update'}]}],
               'template': '...',
               'title': {'font': {'color': 'Black', 'size': 22},
                         'text': '<b>Intertopic Distance Map</b>',
                         'x': 0.5,
                         'xanchor': 'center',
                         'y': 0.95,
                         'yanchor': 'top'},
               'width': 650,
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'range': [2.5526933670043945, 12.541223526000977],
                         'title': {'text': ''},
                         'visible': False},
               'yaxis': {'anchor': 'x',
                         'domain': [0.0, 1.0],
                         'range': [0.24773752689361572, 13.033843040466309],
                         'title': {'text': ''},
                         'visible': False}}
})

In [49]:
responses.columns

Index(['id', 'section_sis_id', 'section', 'attempt',
       'What components of the experiment are clearer now than they were as a participant What questions do you still have for the experimenter Write 3 5 sentences reflecting on the abstract',
       'Paste the response code you received after participating in the graphics experiment here',
       'As of today I am at least 19 years of age',
       'My instructor may share my reflection responses with the researchers in this study',
       'What do you think the purpose of the experiment was',
       'What elements of experimental design such as randomization or the use of a control group do you think were present in the experiment Why',
       'What hypotheses might the experimenter have been testing',
       'What sources of error are involved in this experiment',
       'What variables were examined For each variable identify whether it was quantitative or categorical',
       'In this class you ll be learning about the process of scientific investigation What do you think that process looks like from the perspective of a researcher compared to what it looks like from the perspective of someone in the general public who is a consumer of scientific results Write a paragraph at least 3 5 sentences about how you think science happens',
       'How did the information you gained from the components of this project participation post study reflection extended abstract presentation differ',
       'If you had to hear about this study using only the extended abstract or only the presentation which one would you prefer Which one would be better for determining whether the experiment was well designed',
       'What components were emphasized in the presentation that weren t emphasized in the abstract Why do you think that is',
       'What critiques do you have of this study and its design What would have made the study better'],
      dtype='object')

In [48]:
responses.dtypes

id                                                                                                                                                                                                                                                                                                                                                                         object
section_sis_id                                                                                                                                                                                                                                                                                                                                                             object
section                                                                                                                                                                                                                                                                                                                                                                     int64
attempt                                                                                                                                                                                                                                                                                                                                                                     int64
What components of the experiment are clearer now than they were as a participant What questions do you still have for the experimenter Write 3 5 sentences reflecting on the abstract                                                                                                                                                                                     object
Paste the response code you received after participating in the graphics experiment here                                                                                                                                                                                                                                                                                   object
As of today I am at least 19 years of age                                                                                                                                                                                                                                                                                                                                    bool
My instructor may share my reflection responses with the researchers in this study                                                                                                                                                                                                                                                                                         object
What do you think the purpose of the experiment was                                                                                                                                                                                                                                                                                                                        object
What elements of experimental design such as randomization or the use of a control group do you think were present in the experiment Why                                                                                                                                                                                                                                   object
What hypotheses might the experimenter have been testing                                                                                                                                                                                                                                                                                                                   object
What sources of error are involved in this experiment                                                                                                                                                                                                                                                                                                                      object
What variables were examined For each variable identify whether it was quantitative or categorical                                                                                                                                                                                                                                                                         object
In this class you ll be learning about the process of scientific investigation What do you think that process looks like from the perspective of a researcher compared to what it looks like from the perspective of someone in the general public who is a consumer of scientific results Write a paragraph at least 3 5 sentences about how you think science happens    object
How did the information you gained from the components of this project participation post study reflection extended abstract presentation differ                                                                                                                                                                                                                           object
If you had to hear about this study using only the extended abstract or only the presentation which one would you prefer Which one would be better for determining whether the experiment was well designed                                                                                                                                                                object
What components were emphasized in the presentation that weren t emphasized in the abstract Why do you think that is                                                                                                                                                                                                                                                       object
What critiques do you have of this study and its design What would have made the study better                                                                                                                                                                                                                                                                              object
dtype: object